apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-icons
  description: Component with simple icon links
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  links:
    - title: Prometheus
      url: https://google.ch
      icon: prometheus
    - title: Grafana
      url: https://google.ch
      icon: grafana
    - title: Google BigQuery
      url: https://google.ch
      icon: googlebigquery
    - title: 1.1.1.1
      url: https://google.ch
     
